site_name: "SIFKA---Sistem-Informasi-Fasilitas-Kampus Documentation"
site_description: "Documentation"
site_url: "https://ramjitampan.github.io/SIFKA---Sistem-Informasi-Fasilitas-Kampus/"

repo_name: "ramjitampan/SIFKA---Sistem-Informasi-Fasilitas-Kampus"
repo_url: "https://github.com/ramjitampan/SIFKA---Sistem-Informasi-Fasilitas-Kampus"

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

plugins:
  - search
  - i18n:
      languages:
        - locale: id
          name: Bahasa Indonesia
          build: true
        - locale: en
          default: true
          name: English
          build: true
  - swagger-ui-tag
  # - render_swagger
  - git-revision-date-localized:
      enable_creation_date: !ENV [CI, false]
      fallback_to_build_date: true

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - FE Context: FE_Context.md
  - Components: components.md
  - Data Fetching: data-fetching.md
  - Design System: design-system.md
  - Error Handling: error-handling.md
  - I18n: i18n.md
  - Layout: layout.md
  - Map Behavior: map-behavior.md
  - Motion: motion.md
  - Rules: rules.md
  - Testing: testing.md
